apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: member-roles
objects:

- kind: Role
  apiVersion: rbac.authorization.k8s.io/v1
  metadata:
    name: approve-operator-update
    labels:
      provider: ksctl
  rules:
  - apiGroups:
    - operators.coreos.com
    resources:
    - "installplans"
    verbs:
    - "get"
    - "list"
    - "create"
    - "patch"
    - "update"
    - "delete"

- kind: Role
  apiVersion: rbac.authorization.k8s.io/v1
  metadata:
    name: restart-deployment
    labels:
      provider: ksctl
  rules:
  - apiGroups:
    - apps
    resources:
    - deployments
    verbs:
    - "get"
    - "list"
    - "patch"
    - "update"

- kind: Role
  apiVersion: rbac.authorization.k8s.io/v1
  metadata:
    name: view-secrets
    labels:
      provider: ksctl
  rules:
  - apiGroups:
    - ""
    resources:
    - "secrets"
    verbs:
    - "get"
    - "list"

- kind: Role
  apiVersion: rbac.authorization.k8s.io/v1
  metadata:
    name: edit-secrets
    labels:
      provider: ksctl
  rules:
  - apiGroups:
    - ""
    resources:
    - "secrets"
    verbs:
    - "get"
    - "list"
    - "watch"
    - "create"
    - "update"
    - "patch"

- kind: Role
  apiVersion: rbac.authorization.k8s.io/v1
  metadata:
    name: edit-csv
    labels:
      provider: ksctl
  rules:
  - apiGroups:
    - operators.coreos.com
    resources:
    - "clusterserviceversions"
    verbs:
    - "get"
    - "list"
    - "patch"
    - "update"
